spring:
  application:
    name: ai
  config:
    import: optional:file:.env[.properties]
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    mcp:
      client:
        connections:
          webflux-mcp-server:
            url: http://localhost:8098/mcp/messages

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
#  ai:
#    openai:
#      api-key: ${OPENAI_API_KEY}
#    stdio:
#      root-change-notification: false
#      connections:
#        server1:
#          command: http://localhost:8080/mcp-server
#          sse-endpoint: /sse
#          args:
#            - --port=8080
#            - --mode=production
#          env:
#            API_KEY: ${OPENAI_API_KEY}
#            DEBUG: "true"


jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-validity-in-milliseconds: 3600000 # 1 hour
  refresh-token-validity-in-milliseconds: 1209600000 # 14 days

server:
  port: 8089
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka