spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1-mini
    mcp:
      client:
        enabled: true
        request-timeout: 60s
        sse:
          connections:
            webflux-mcp-server:
              url: ${MCP_SERVER_SVC_URI}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH_JWKS_URI}

jwt:
  audience:  ${AUTH_INTERNAL_AUDIENCE}
